from .auth import auth_bp
from .interview import interview_bp
from .interview_planning import interview_planning_bp
from .interview_session import interview_session_bp
from .question_generation import question_bp
from .voice import voice_bp
from .reading import reading_bp
from .presentation_upload import presentation_upload_bp
from .candidate_intelligence import candidate_bp
from .analytics import analytics_bp
from .reports import reports_bp
from .recommendations import recommendations_bp
from .history import history_bp
from .modes import modes_bp
